version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/UserApp"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "📦 deps:"
